#!/usr/bin/env bash

if
  [[ -s "/home/gentle6318/.rvm/gems/ruby-2.2.2@global/environment" ]]
then
  source "/home/gentle6318/.rvm/gems/ruby-2.2.2@global/environment"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/gentle6318/.rvm/gems/ruby-2.2.2@global/environment'" >&2
  exit 1
fi
